"""migração automática

Revision ID: a16bd22113ef
Revises: 
Create Date: 2025-06-21 07:07:51.828587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a16bd22113ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('lesson_type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_type_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'lesson_types', ['lesson_type_id'], ['id'])

    # ### end Alembic commands ###
