"""Adiciona lesson_type_id à tabela students

Revision ID: c2fdfeb181fd
Revises: 
Create Date: 2025-05-25 14:00:10.673056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2fdfeb181fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_type_id', sa.Integer(), nullable=True))
        # Adiciona um nome explícito para a restrição de chave estrangeira
        batch_op.create_foreign_key('fk_students_lesson_type_id', 'lesson_types', ['lesson_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        # Usa o mesmo nome da restrição que foi criada no upgrade
        batch_op.drop_constraint('fk_students_lesson_type_id', type_='foreignkey')
        batch_op.drop_column('lesson_type_id')

    # ### end Alembic commands ###
